FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

CMD ["sh", "-c", "alembic upgrade head && uvicorn backend.main:app --reload --reload-dir backend --host 0.0.0.0 --port 8000"]
