"""initial schema

Revision ID: 9a60d2247d8d
Revises: 
Create Date: 2026-03-25 11:02:44.473013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a60d2247d8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alphas',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('universe', sa.Text(), nullable=False),
    sa.Column('region', sa.Text(), nullable=False),
    sa.Column('delay', sa.Integer(), nullable=False),
    sa.Column('decay', sa.Integer(), nullable=False),
    sa.Column('neutralization', sa.Text(), nullable=False),
    sa.Column('truncation', sa.Float(), nullable=False),
    sa.Column('pasteurization', sa.Text(), nullable=False),
    sa.Column('nan_handling', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.Text(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('filter_skipped', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['alphas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proxy_prices',
    sa.Column('ticker', sa.Text(), nullable=False),
    sa.Column('date', sa.Text(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('adj_close', sa.Float(), nullable=True),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ticker', 'date')
    )
    op.create_table('runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('candidates_gen', sa.Integer(), nullable=False),
    sa.Column('candidates_pass', sa.Integer(), nullable=False),
    sa.Column('llm_theme', sa.Text(), nullable=True),
    sa.Column('gp_generations', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('finished_at', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pool_correlations',
    sa.Column('alpha_a', sa.Text(), nullable=False),
    sa.Column('alpha_b', sa.Text(), nullable=False),
    sa.Column('correlation', sa.Float(), nullable=False),
    sa.Column('computed_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['alpha_a'], ['alphas.id'], ),
    sa.ForeignKeyConstraint(['alpha_b'], ['alphas.id'], ),
    sa.PrimaryKeyConstraint('alpha_a', 'alpha_b')
    )
    op.create_table('simulations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alpha_id', sa.Text(), nullable=False),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.Column('fitness', sa.Float(), nullable=True),
    sa.Column('returns', sa.Float(), nullable=True),
    sa.Column('turnover', sa.Float(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('wq_sim_id', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['alpha_id'], ['alphas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simulations')
    op.drop_table('pool_correlations')
    op.drop_table('runs')
    op.drop_table('proxy_prices')
    op.drop_table('alphas')
    # ### end Alembic commands ###
